### ISSUE TITLE
Crate Universe Examples failing on Bazel CI

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/rules_rust#1459]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2547#0181f78e-db8f-42ac-9f3d-610ff8e146ba

There's not much information to go by other than "exit status: 1". Could you please look into this? (and potentially fix the test to produce more meaningful error messages)

**Comment by UebelAndre** [comment]
I'm surprised to see such a useless error. How would I go about reproducing this? It doesn't seem to happen in any of our current CI jobs. Looking at the code I'm wondering if I'm somehow messed up the bash here? https://github.com/bazelbuild/rules_rust/blob/main/crate_universe/private/crates_vendor.bzl#L9-L16 other than that I need some repro and way to iterate to get more information.

**Comment by Wyverald** [comment]
I should mention that this is with Bazel@HEAD. Could you try to reproduce with `USE_BAZEL_VERSION=last_green bazelisk ...`?

**Comment by scentini** [comment]
Actually it looks like Windows is doing fine.

**Comment by meteorcloudy** [comment]
It seems the cause is https://github.com/bazelbuild/rules_rust/blob/53ad14eead1a194bd740ff8605a12c4fccdb3ed8/crate_universe/private/crates_vendor.bzl#L9-L14 introduced at https://github.com/bazelbuild/rules_rust/commit/53ad14eead1a194bd740ff8605a12c4fccdb3ed8 not working with our CI setup.

On Bazel CI, The `bazel` in PATH is actually the bazelisk binary. 

In the main pipeline built with Bazel 5.2.0. When running `bazel run //vendor_external:crates_vendor`, the shell script can locate the actual bazel binary (not the bazelisk binary!) because Bazelisk actually adds the directory of the downloaded Bazel binary into PATH, see https://github.com/bazelbuild/bazelisk/blob/37c5a9587fc1d3d784ae5505d61af8484e270d3a/core/core.go#L429
This works with the follow up steps because `BAZEL_REAL` points to an actual Bazel binary.

In the downstream pipeline with Bazel@HEAD, we actually run `/tmp/tmpmszd1jhw/bazel run //vendor_external:crates_vendor`. `/tmp/tmpmszd1jhw/bazel` is a real Bazel binary built from HEAD, so it won't add anything to `PATH`. The shell script will locate `bazel` from `PATH`, which actually points to the Bazelisk binary, which doesn't work with the follow up steps.

I can reproduce this in the following way:

1. Download Bazelisk and rename it to `bazel` and make sure its in your `PATH`
```
mkdir tmp
wget https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-darwin-amd64 -O ./tmp/bazel
chmod +x ./tmp/bazel
export PATH=$PWD/tmp:$PATH
```
2. Download another Bazel binary and run
```
wget https://github.com/bazelbuild/bazel/releases/download/5.2.0/bazel-5.2.0-darwin-x86_64 -O ./tmp/bazel-5.2.0
chmod +x ./tmp/bazel-5.2.0
./tmp/bazel-5.2.0 run //vendor_external:crates_vendor
...
INFO: Analyzed target //vendor_external:crates_vendor (74 packages loaded, 1820 targets configured).
INFO: Found 1 target...
Target //vendor_external:crates_vendor up-to-date:
  bazel-bin/vendor_external/crates_vendor.sh
INFO: Elapsed time: 343.534s, Critical Path: 0.53s
INFO: 57 processes: 57 internal.
INFO: Build completed successfully, 57 total actions
INFO: Build completed successfully, 57 total actions
Error: exit status: 1
```


You can add get more debug info by the following patch:
```
diff --git a/crate_universe/private/crates_vendor.bzl b/crate_universe/private/crates_vendor.bzl
index 0ebfa42..a5fb3e1 100644
--- a/crate_universe/private/crates_vendor.bzl
+++ b/crate_universe/private/crates_vendor.bzl
@@ -7,7 +7,9 @@ load("//rust/platform:triple_mappings.bzl", "SUPPORTED_PLATFORM_TRIPLES")

 _UNIX_WRAPPER = """\
 #!/usr/bin/env bash
+set -x
 set -euo pipefail
+echo $PATH
 export RUNTIME_PWD="$(pwd)"
 if [[ -z "${{BAZEL_REAL:-}}" ]]; then
     BAZEL_REAL="$(which bazel || echo 'bazel')"
```

**Comment by meteorcloudy** [comment]
OK I changed our CI setup to always use Bazelisk, it's working now: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2547#0181fcc1-308d-4764-a315-51af070bd98a
