### ISSUE TITLE
version check misfires

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/rules_rust#148]
Ran into 
```
ERROR: while parsing '//third_party/rust/gssapi:all': error loading package 'ext/public/rustgssapi': Extension file not found. Unable to load package for '@bazel_version//:def.bzl': The repository could not be resolved
ERROR: while parsing '//third_party/rust/gssapi:all': error loading package 'ext/public/rustgssapi': Extension file not found. Unable to load package for '@bazel_version//:def.bzl': The repository could not be resolved
```

@mhlopko I imagine this has something to do with the treatment of recursive workspaces..

our WORKSPACE includes

```
local_repository(
    name = "io_bazel_rules_rust",
    # Vendored from 4a9d0e0b6c66f1e98d15cbd3cccc8100a0454fc9
    path = __workspace_dir__ + "/third_party/bazelbuild/rules_rust",
)

custom_register_rust_toolchains()
```

---
@acmcarther can we block CI on one of the cargo-raze example repos? This would have caught 
- https://github.com/google/cargo-raze/pull/60
- https://github.com/google/cargo-raze/issues/69
and maybe some of the version check issues.

**Comment by acmcarther** [comment]
**W.R.T. version check**

I encountered this yesterday but neglected to create an issue. I couldn't tell at a glance if the version checks were intended to fire for users, or just in the context of local (rules_rust) development.

I had to include the following

*WORKSPACE*
```python
http_archive(
    name = "bazel_skylib",
    sha256 = "b5f6abe419da897b7901f90cbab08af958b97a8f3575b0d3dd062ac7ce78541f",
    strip_prefix = "bazel-skylib-0.5.0",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/0.5.0.tar.gz",
)

load(":workspace.bzl", "bazel_version")

bazel_version(name = "bazel_version")
```

*workspace.bzl*
```python
load("@bazel_skylib//lib:versions.bzl", "versions")

def _store_bazel_version(repository_ctx):
    bazel_version = versions.get()
    if len(bazel_version) == 0:
        print("You're using development build of Bazel, " +
              "make sure it's at least version 0.17.1")
    elif versions.is_at_most("0.17.0", bazel_version):
        fail("Bazel %s is too old to use with rules_rust, please use at least Bazel 0.17.1, preferably newer." % bazel_version)
    repository_ctx.file("BUILD", "exports_files(['def.bzl'])")
    repository_ctx.file("def.bzl", "BAZEL_VERSION='" + bazel_version + "'")

bazel_version = repository_rule(
    implementation = _store_bazel_version,
)
```

If these are intended to be user-facing then we should add the WORKSPACE content to the [rust_repositories function](https://github.com/bazelbuild/rules_rust/blob/5ec0b832d6a7a7ad183cfb9fb99ff2cf91429caa/rust/repositories.bzl#L6-L32).

---

**W.R.T. blocking CI**
I'm not totally clear what the suggestion is. Did you want to block *this* repository on smoketests that use cargo-raze? Or was it the other way around. I'm generally amenable to either, though I really want to finish https://github.com/google/cargo-raze/pull/54 before using cargo-raze here just so that all CI supported platforms can have working compilations.

**Comment by mfarrugi** [comment]
#167
