### ISSUE TITLE
crate.annotation version wildcard does not match prerelease versions

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_rust#1690]
The `"*"` default value for the `version` attribute appears not to match prerelease versions of crates. For example, I was trying to add an annotation for launchdarkly-server-sdk 1.0.0-beta.4:

```
        "launchdarkly-server-sdk": [crate.annotation(
            patch_args = ["-p1"],
            patches = ["@//bazel/patches:launchdarkly-rust-server-sdk/0001-remove-use-of-built-crate-to-allow-bazel-to-build.patch"],
        )],
```

This produces:

> Error: Unused annotations were provided. Please remove them: [CrateId { name: "launchdarkly-server-sdk", version: "*" }]

If I add `version = "1.0.0-beta.4"`, then it works.

This is like the crates_universe version of https://github.com/google/cargo-raze/issues/419. Do they use the same underlying library for version matching or something?

**Comment by illicitonion** [comment]
Yeah, at their code both use the semver crate, specifically this bit of code: https://github.com/bazelbuild/rules_rust/blob/70b272aaddce189ad0a946094a85a1b1964864da/crate_universe/src/config.rs#L359-L365

I suspect the cleanest fix for this would be to make version optional, rather than default to `*`. The steps that'd take would roughly be:
1. Make this be an `Option<String>`: https://github.com/bazelbuild/rules_rust/blob/70b272aaddce189ad0a946094a85a1b1964864da/crate_universe/src/config.rs#L336-L337 (or possibly a custom `enum VersionReq { Any, Semver(String) }`
2. Change https://github.com/bazelbuild/rules_rust/blob/70b272aaddce189ad0a946094a85a1b1964864da/crate_universe/private/crate.bzl#L64 from defaulting to `*` to defaulting to `None`. Technically this is a breaking change, but not one I imagine anyone will notice.
3. Change the matching logic to return `true` if `version.is_none()` here: https://github.com/bazelbuild/rules_rust/blob/main/crate_universe/src/config.rs#L359-L365
4. Fix up all the type errors and assumed-present errors along the way.
5. Make sure there's a test for the behaviour.

I'd be happy to review a PR if you wanted to put it together, I don't think it would be a huge amount of work :)

**Comment by jfirebaugh** [comment]
I started down this path. However, I think there is at least one use of `CrateId` which does not want these extended semantics, namely https://github.com/bazelbuild/rules_rust/blob/2f0511782f3706bc8a64cc8e051864e4daeac2bb/crate_universe/src/context/crate_context.rs#L16
It looks like in this context `CrateId` is used to identify workspace dependencies rather than the target of an annotation. I assume that an optional semver specifier would be inappropriate there. Should I create a new type to selectively replace only the uses of `CrateId` associated with annotations?

Also, where should I add tests? I can add a unit test for the updated `matches` function obviously, but I feel like there should also be a test that involving Starlark code that actually uses `crate.annotation`. The closest thing I've found so far are the examples. Should I add another example as an end-to-end test?

**Comment by jfirebaugh** [comment]
Alternative proposal: just change `matches` to treat `"*"` as a true "match anything" wildcard, instead of delegating to semver for `"*"`. Don't change anything else. Don't make version optional; don't make a distinction between `None` and `Some("*")`. This change is trivial to implement.
