### ISSUE TITLE
crate_universe: exposing the bazel lockfile format

### ISSUE THREAD

**Issue by Calsign** [bazelbuild/rules_rust#1725]
Hello. I am making a [gazelle](https://github.com/bazelbuild/bazel-gazelle) plugin for rust for automatic build file management: https://github.com/Calsign/gazelle_rust

One of the things that the gazelle plugin handles is dependencies on external crates pulled in through crate_universe. This requires parsing lockfiles. Depending on the configuration, rules_rust currently uses both cargo lockfiles (`Cargo.lock`) and custom "bazel lockfiles" (`Cargo.Bazel.lock`). While it is not currently possible to go fully cargo-free (i.e., no `Cargo.lock`), [this comment](https://github.com/bazelbuild/rules_rust/issues/1674#issuecomment-1330900533) suggests that allowing a cargo-free setup is desired. Thus to support cargo-free mode, the gazelle plugin needs to be able to parse bazel lockfiles.

Parsing bazel lockfiles is tricky because the interface is not exposed and it is subject to change across rules_rust versions. My current approach involves [depending on cargo_bazel](https://github.com/Calsign/gazelle_rust/blob/main/rust_parser/BUILD.bazel#L22) from the version of rules_rust used in each project and [patching rules_rust](https://github.com/Calsign/gazelle_rust/blob/main/patches/rules_rust.patch) to expose the required modules from cargo_bazel (`context` and `utils`). This is suboptimal.

I would like the gazelle plugin to be usable without needing to patch rules_rust. What's the best approach here? I'm thinking the `context` and `utils` modules could be split out into a separate crate that is publicly exposed. (This would also make the gazelle plugin build faster.) Is that reasonable? If so, I'm happy to put up the PR, just wanted to open a discussion first.

Separately it could make sense to integrate the gazelle plugin into rules_rust if that is desired. But I'll open a different issue for that.

**Comment by illicitonion** [comment]
Thanks for filing this issue, gazelle for Rust is a really useful project, and I'm excited to try it out myself!

I'm definitely on board with parsing information out of `Cargo.Bazel.lock` being a good way to get this information, rather than re-implementing the parsing. I'd also be open to potentially adding extra information to the lockfile if it's needed, depending on what the information ends up being (we did similar for rules_jvm_external to make it easier to write a gazelle plugin for Java: https://github.com/bazelbuild/rules_jvm_external/pull/716).

I don't think we should just open up `Context` as-is to be public - it contains a bunch of extra data in it that you probably _don't_ need, and a lot of its structure is implementation details that I don't think we want to lock into a public API. Right now, we have freedom to change it largely however we want, because the digest in it necessarily changes every time we change the cargo-bazel version, so we haven't had to think much about compatibility.

Looking at what you're actually using [here](https://github.com/Calsign/gazelle_rust/blob/ca7ef4f31bc98f5d33ae969987d4163e5c5054a3/rust_parser/lockfile_crates.rs#L23-L70), it looks like your need would be fulfilled by a public API that looks like this?

```rust
pub struct CrateInfo {
  pub name: String,
  pub version: semver::Version,
  pub library_target_name: Option<String>,
  pub is_proc_macro: bool,
}

pub Config(String);

pub struct SelectList<T: Ord> { ... }

pub trait HasDeps {
  fn get_deps(&self) -> SelectList<CrateInfo>;
}

pub trait HasWorkspaceMembers {
  fn get_workspace_members(&self) -> Vec<impl HasDeps>
}
```

Is that correct? If so, I think I'd be happy to add a function which could parse a lockfile to an `impl HasWorkspaceMembers` to `crate_universe`, and expose it publicly from `cargo_bazel` (and if its compile time is a problem, I'm sure we could work out some shenanigans to extract a sub-crate for this purpose). (I don't think you actually need `SelectList` right now, we could just give you a `Vec`, but I think you will soon).


How does that sound to you? (And how does it sound to @UebelAndre too?)

**Comment by illicitonion** [comment]
> Separately it could make sense to integrate the gazelle plugin into rules_rust if that is desired. But I'll open a different issue for that.

I'd also be generally in favour of that, but agree it should probably be a separate discussion, and more people would have opinions :)

**Comment by UebelAndre** [comment]
> > Separately it could make sense to integrate the gazelle plugin into rules_rust if that is desired. But I'll open a different issue for that.
> 
> I'd also be generally in favour of that, but agree it should probably be a separate discussion, and more people would have opinions :)

I'd really like to avoid committing Golang to rules_rust. I've been very unhappy with how invasive Golang can be with it's explosive dependency tree and how unresponsive maintainers of `rules_go` and `bazel_gazelle` seem to be around this. Would it be possible to define a plugin in Rust?

**Comment by Calsign** [comment]
@illicitonion I agree, this definitely doesn't require all of `Context`. Something like that API would be great. I only mention compile time because building cargo_bazel is currently the long pole for the Rust part of the gazelle plugin, which is a little silly, so splitting out this interface would be nice to have.

@UebelAndre It's definitely worth having a discussion :slightly_smiling_face: There was the proposed subprocess API for gazelle (https://github.com/bazelbuild/bazel-gazelle/issues/938), but I haven't seen it go anywhere. My sense is that it's best to write part of the plugin in golang, as I have done. Plus the integration tests would require rules_go and gazelle anyway.
