### ISSUE TITLE
process_wrapper requires a newer glibc version than rust

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_rust#1954]
I think `rules_rust` should match the glibc requirements of rust itself (2.17), but it requires 2.33.

**Comment by UebelAndre** [comment]
The process-wrapper is built with whatever toolchains you have configured right? Is there something encoded in `rules_rust` that requires the newer version?

**Comment by duarten** [comment]
Hum.. I thought process-wrapper was being distributed as a binary. We saw this error when trying to run a rust target on a distribution with glibc @ 2.31:

```
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper)
```

**Comment by UebelAndre** [comment]
It's not distributed by rules_rust. There are some sorta bootstrapping steps where custom `rustc` actions invoke `rustc` to compile the process-wrapper without the use of the process-wrapper and then the rest of your targets use the compiled process-wrapper. Any use of glibc is likely caused by the host you compile on. If you use a remote cache, this can occur when you compile on a newer system and then get a cache hit on the older one. But `rules_rust` doesn't ship a pre-compiled process-wrapper.

**Comment by duarten** [comment]
Hum.. not using any remote cache. I'm using zig for cross-compilation and zig ships its own libc version, so maybe there's some oddness related to that. Anyways, closing since the problem doesn't exist. Thanks! :)
