### ISSUE TITLE
Allow setting default rustc_flags

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/rules_rust#212]
Found myself wanting to set 
```
    rustc_flags = [
        "--deny=warnings",
        "--allow=deprecated",
    ],
```
globally, and was trying to decide whether to modify rust_toolchain or use an internal `rust_library` macro. 

If the toolchain provides default flags, they would be passed to cargo-raze generated dependenices.. which is fine for lints (since generated files have `--cap-lints=allow`), but might not be fine for other flags.

Does anyone have thoughts on whether this belongs in rust_toolchain or not?

**Comment by m3rcuriel** [comment]
IMO this is what project specific macros are for, but I'm a minimalist at heart.

As usual, reaching for the C++ side of it, default arguments can be set via the toolchain configuration, and that does run into problems where it's getting passed to things it shouldn't be. For example (not sure if still broken), Go stdlib wouldn't build with my C++ CROSSTOOL because it had a lot of warnings that I was explicitly marking as errors. In C++, at least, I believe that the `-Wno-` tend to overrule the `-W` options. I'm not sure how rust would handle conflicting flags like that.

**Comment by hlopko** [comment]
In C++, Proto, or Java rules we have options that add flags to all relevant actions (not replace, add). Those are e.g. `--copt`, `--linkopt, `--javacopt`, `--protocopt` and others. I think it makes perfect sense to also have a corresponding [build_settings](https://docs.bazel.build/versions/master/skylark/config.html) for rules_rust.

**Comment by UebelAndre** [comment]
As of `v0.18.0`, `--@rules_rust//:extra_rustc_flags` (https://github.com/bazelbuild/rules_rust/pull/566) and `--@rules_rust//:extra_rustc_flag` (https://github.com/bazelbuild/rules_rust/pull/1413) introduced. I think this satisfies the request but I'm happy to reopen if that's not the case.

**Comment by joneshf** [comment]
It looks like the added flags–`--@rules_rust//:extra_rustc_flag` and `--@rules_rust//:extra_rustc_flags`–are also added to any `rustc` calls for `external` repositories. The reason this is an issue for me is that I want to add a flag that some third-party code doesn't compile with (like denying a lint).

I'm not sure if that's intentional, but it looks like something naïve like the following patch makes it not propagate the flags:
```patch
diff --git a/rust/private/rustc.bzl b/rust/private/rustc.bzl
index 01838f84..d999e059 100644
--- a/rust/private/rustc.bzl
+++ b/rust/private/rustc.bzl
@@ -1046,20 +1046,20 @@ def construct_arguments(
         rustc_flags.add_all(toolchain.extra_rustc_flags)
 
     # extra_rustc_flags apply to the target configuration, not the exec configuration.
-    if hasattr(ctx.attr, "_extra_rustc_flags") and not is_exec_configuration(ctx):
+    if hasattr(ctx.attr, "_extra_rustc_flags") and not is_exec_configuration(ctx) and ctx.label.workspace_root == "":
         rustc_flags.add_all(ctx.attr._extra_rustc_flags[ExtraRustcFlagsInfo].extra_rustc_flags)
 
-    if hasattr(ctx.attr, "_extra_rustc_flag") and not is_exec_configuration(ctx):
+    if hasattr(ctx.attr, "_extra_rustc_flag") and not is_exec_configuration(ctx) and ctx.label.workspace_root == "":
         rustc_flags.add_all(ctx.attr._extra_rustc_flag[ExtraRustcFlagsInfo].extra_rustc_flags)
 
     if hasattr(ctx.attr, "_per_crate_rustc_flag") and not is_exec_configuration(ctx):
         per_crate_rustc_flags = ctx.attr._per_crate_rustc_flag[PerCrateRustcFlagsInfo].per_crate_rustc_flags
         _add_per_crate_rustc_flags(ctx, rustc_flags, crate_info, per_crate_rustc_flags)
 
-    if hasattr(ctx.attr, "_extra_exec_rustc_flags") and is_exec_configuration(ctx):
+    if hasattr(ctx.attr, "_extra_exec_rustc_flags") and is_exec_configuration(ctx) and ctx.label.workspace_root == "":
         rustc_flags.add_all(ctx.attr._extra_exec_rustc_flags[ExtraExecRustcFlagsInfo].extra_exec_rustc_flags)
 
-    if hasattr(ctx.attr, "_extra_exec_rustc_flag") and is_exec_configuration(ctx):
+    if hasattr(ctx.attr, "_extra_exec_rustc_flag") and is_exec_configuration(ctx) and ctx.label.workspace_root == "":
         rustc_flags.add_all(ctx.attr._extra_exec_rustc_flag[ExtraExecRustcFlagsInfo].extra_exec_rustc_flags)
 
     if _is_no_std(ctx, toolchain, crate_info):
```
