### ISSUE TITLE
Problem building external crate `uniffi_testing`

### ISSUE THREAD

**Issue by StuartHarris** [bazelbuild/rules_rust#2271]
I'm using `crate_universe` to build my dependencies, which includes [`uniffi_testing`](https://github.com/mozilla/uniffi-rs). This crate has a reference in [`lib.rs`](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_testing/src/lib.rs#L158) to `env!("CARGO")`, which is not set and so it won't compile. I have tried `--action_env=CARGO="$(which cargo)"`, but it seems this only sets the variable for crates that have a build script (which is not true for `uniffi_testing`).

Is there a way to to inject this env var when using `crate_universe` and `all_crate_deps`?

**Comment by illicitonion** [comment]
Depending on what the `cargo build` in this crate is meant to do, this may or may not be useful, as it may be expecting a bunch of other stuff to be present at runtime (e.g. a set of `Cargo.toml` files), but here are some building blocks that may be helpful for you to work out what's needed:

1. rules_rust exposes `$(CARGO)` as a [make variable](https://bazel.build/reference/be/make-variables), just like it does `$(RUSTC)` which you can see [in this example](https://github.com/bazelbuild/rules_rust/blob/f11c529e802ee1a4537634d4a175bd6658dd60be/test/cargo_build_script/tools_exec/BUILD.bazel#L6-L23). So if you add `"//rust/toolchain:current_rust_toolchain"` to a target's `toolchains` attribute, it should be able to reference `$(CARGO)` (which you'll need to do from `rustc_env` not from `build_script_env`). [`crate.annotation`](http://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation) currently lets you add to `rustc_env`, but doesn't let you add to `toolchains`, so you'll probably need to add that ability and thread the information through to target generation (this isn't too fiddly, if you grep for `build_script_proc_macro_deps` you should see the pattern you need to follow).
2. It's probably not correct to look up the path to cargo at compile time, it should probably actually be done at runtime - I'd recommend patching the crate (and upstreaming it) so that it uses `std::env::var_os("CARGO")`, and maybe falls back to `env!("CARGO")` if it wasn't set. Then you probably want to thread through `$(CARGO)` as an `env` value on the test, rather than as a `rustc_env` on the compile.

**Comment by StuartHarris** [comment]
Thanks for the pointers, they really helped :-) 
I agree with point 2, but even better would be to use cargo as a library, will see what I can do.
Btw, I couldn't find a pattern for threading the variables through by grepping `build_script_proc_macro_deps`, though.
