### ISSUE TITLE
undefined symbol: backtrace_syminfo

### ISSUE THREAD

**Issue by ghost** [bazelbuild/rules_rust#253]
## Environment

**Platform**: `Ubuntu 19.04`
**JDK**: 8
**Rust Edition**: `2018`
**Bazel Version**:`0.28.1`
**rules rust version**: `f727669b8ac3c9d237ed9bc7833b8e1eeec90506`

## Reproducing Project Sample

https://github.com/rustacian/Rust-Bazel-JNI

## Problem

I'm attempting to build and invoke a [rust shared library](https://github.com/rustacian/Rust-Bazel-JNI/blob/master/src/lib.rs) using rust-jni. When calling certain Rust methods I get an error `undefined symbol: backtrace_syminfo`: 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/libccsimple.so: /home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_S_Cccsimple___U/libsimple-1678821589.so: undefined symbol: backtrace_syminfo
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at JNI.<clinit>(JNI.java:4)
```
From inspecting the shared object constructed in bazel-bin with `readelf --symbols` (or `nm`) I can see:

```
   171: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND backtrace_syminfo
   172: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND backtrace_pcinfo
   173: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND backtrace_create_state
```

I believe those symbols are entering via inclusion through error-chain in jni-rs https://github.com/jni-rs/jni-rs/blob/master/Cargo.toml#L36-L39

Not too sure how to debug this one. What do you think is a good avenue to pursue?

**Comment by mfarrugi** [comment]
I would look at whether a cargo built version of `libccsimple.so` differs from the bazel built version (namely its dependencies and/or RPATH). I suspect bazel is not capturing/propagating the backtrace dependency correctly.

I don't remember exactly how shared library dependency resolution works, but I also vaguely recall the native code needing LD_LIBRARY_PATH set in addition to (or instead of?) `java.library.path`. I think it was something like Java only needs to know about the specific .so you're interested in, but then ld needs to know where to find the dependencies.

Does the repro project print the output in it's README, or the exception in this issue?

**Comment by rustacian** [comment]
> Does the repro project print the output in it's README, or the exception in this issue?

In the current state, it should print the exception, but in prior runs without [this method](https://github.com/rustacian/Rust-Bazel-JNI/blob/master/src/JNI.java#L8 
) defined in either Java or Rust, it did in fact print the message in the README. From other issues with JNI/Bazel I noted that the library path would be set if one of the dependencies was a `cc_binary`, and as for `LD_LIBRARY_PATH` this PR/issue seems relevant https://github.com/bazelbuild/bazel/pull/7042#issue-242398473

I'll get back to you on those suggestions, once I've had a chance to do them.

**Comment by rustacian** [comment]
Some differences I can note already: the bazel version using local_jdk copies all my shared objects into the `runfiles` of the project, and sets java.library.path to include that:

```
/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Slib_Samd64_Sjli:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Slib_Samd64:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Sjre_Slib_Samd64_Sjli:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Sjre_Slib_Samd64:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Sjre_Slib_Samd64_Sserver:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___Uexternal_Slocal_Ujdk_Sjre_Slib_Sext:/home/rustacian/.cache/bazel/_bazel_rustacian/2a34aa520791c0c09410be28bf2e9925/execroot/__main__/bazel-out/k8-fastbuild/bin/Main.runfiles/__main__/_solib_k8/_U_S_S_Cwrapper___U
```

Whereas the non-bazel version just uses the system's library settings from ldconfig and correctly loads all the dependent libraries.

```
target/debug:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
```


Secondly, the symbols differ in each built shared object.

- Bazel built symbols  https://gist.github.com/rustacian/a718375e8d57d5624d2e0ca08d17e3fa
- Cargo built symbols https://gist.github.com/rustacian/c3c473a07182055992fabe3612ebfee3

One thing I notice is the absence of non-prefixed backtrace symbols in the Cargo-built shared object. Bit of a longshot, but possibly I'm not running a required `build.rs` somewhere which should be prefixing those? https://github.com/rust-lang/backtrace-rs/commit/390ea2a3b630d5bcb83b02c8c6ce814b9d5df7d8

**Comment by mfarrugi** [comment]
The missing build.rs is definitely a problem, I think it might not specific
at all to using it in shares libraries.

https://github.com/google/cargo-raze/issues/41#issuecomment-439166782 has a
handwritten BUILD for backtrace-sys. I suspect that 1. you could repro with
a pure rust binary (this might be a computer error for a static binary?),
and 2. the working version of your project works because the backtrace
dependency ends up being pruned by the compiler.

**Comment by UebelAndre** [comment]
The examples here have since become unreachable so I'll close this out. Since this has opened there have been many improvements to the ability for `rules_rust` to handle shared libraries as well as the introduction of [crate_universe](https://bazelbuild.github.io/rules_rust/crate_universe.html) for generating external dependencies for multiple platforms. Hopefully those are sufficient to avoid the issues described above.
