### ISSUE TITLE
[BUG] 0.46.0 Selects wrong Tokio version 

### ISSUE THREAD

**Issue by marvin-hansen** [bazelbuild/rules_rust#2689]
This is something I've encounter while converting a WORKSPACE config to MODULE.

When you run the target with Cargo, it builds and runs:

`cargo run --bin server`

When you run the same target with Bazel, if fails with an error:

`bazel run //crates/grpc_server:server`

Error:

`Running command line: target-bzl/bin/crates/grpc_server/server
GreeterServer listening on [::1]:50051
thread 'main' panicked at external/rules_rust~~i~rules_rust_prost__hyper-0.14.26/src/server/tcp.rs:130:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

The error just says that the Tokio version mismatches for some dependencies, meaning some dependencies
expecting a version 1 whereas something else is there. The error is [well explained on SO.](https://stackoverflow.com/questions/64779920/why-do-i-get-the-error-there-is-no-reactor-running-must-be-called-from-the-con) However, I've declared version 1.38 as a dependency.

Versions and features of all deps are identical in Cargo and in Bazel. 

Also, strangely enough, the same error occurs regardless of using a WORKSPACE or MODULE config. 

Repo:
https://github.com/marvin-hansen/bazel_rust_example

**Comment by illicitonion** [comment]
Thanks for the super detailed repro!

I _suspect_ the problem here is that the prost rules themselves have a dependency on tokio, and the version we give by default is probably different from the one you're using. You're pulling this in using the `register_toolchains("@rules_rust//proto/prost:default_prost_toolchain")` line in your MODULE.bazel.

Take a look at https://bazelbuild.github.io/rules_rust/rust_proto.html#customizing-prost-and-tonic-dependencies which specifies how you can supply your own prost toolchain. Basically, you need to supply each of those crates _from your own `crate_universe`_ so that the versions get resolved together.

I haven't managed to get this successfully working yet, but I suspect if you can get into a place where your MODULE.bazel pulls in `protoc-gen-prost`, `prost-types`, `protoc-gen-tonic`, `prost`, and `tonic`, and can point at your version of them rather than rules_rust's, things will start working.

**Comment by marvin-hansen** [comment]
@illicitonion Thank you so much for the pointer. This does makes sense because when I enable RUST_BACKTRACE, I see clearly that rust_prost depends on hyper-0.14, which is not only ancient, but also depends on an outdated Tokio version. 
That at least clears up the actual cause.

The patch mentioned in the docs is conditioned on protoc-gen-prost getting past 0.2.2, which it did quite some time ago.
And indeed, in my internal main monorepo, that uses a very similar configuration, the issues does not occur without any patching, so I am still trying to pinpoint the exact difference between those two Bazelmod configs.

That said, Tokio is the single most widely used async runtime in Rust, therefore it would be really great to remove the internal dependency on hyper-0.14 to remove those conflicting versions altogether. That would make the rules a lot more future proof, robust, and eliminates this toolchain overwrite workaround. And no, I couldn't make it work either when I tried a few months ago, but then I figured out my main repo actually builds without it.

**Comment by marvin-hansen** [comment]
Alright,

thank you for the detailed insight and link to the setup.

As discussed on Slack, I've added a first draft of a custom toolchain Prost config in a separate branch.

https://github.com/marvin-hansen/bazel_rust_example/tree/rust-proto

[Toolchain]( https://github.com/marvin-hansen/bazel_rust_example/blob/rust-proto/build/toolchains/BUILD.bazel)
[MODULE](https://github.com/marvin-hansen/bazel_rust_example/blob/rust-proto/MODULE.bazel)

Still working on the proto compiler workaround; I add a comment  later once that's solved.

Thank you for all your help and taking a look at the  underlying issue.

**Comment by marvin-hansen** [comment]
Solved with a correct custom toolchain thanks to @illicitonion 

https://github.com/marvin-hansen/bazel_rust_example/blob/main/build/prost_toolchain/BUILD.bazel

Updating the Bazelmod docs.

**Comment by zachcoleman** [comment]
Is it possible to use this toolchain with crate universe?
```
crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    ...
```

When I do this, I get:
```
 no such target '@@rules_rust~~crate~cloud_crates//:protoc-gen-prost__protoc-gen-prost'
 ```
 
 I don't know how to resolve using both a set of crates derived from Cargo files and having the necessary set files to run the custom toolchain that is normally build with `crate.from_spec` calls.

**Comment by marvin-hansen** [comment]
That's a known bug.

You have to add the version number to proto gen prost and run build again.
See this example.

https://github.com/bazelbuild/examples/blob/main/rust-examples/08-grpc-client-server/build/prost_toolchain/BUILD.bazel


Also, I recommend vendoring all deps as shown in the example linked above.

**Comment by zachcoleman** [comment]
Unfortunately that is not resolving it for me:
![Screenshot 2024-09-13 at 08 18 25](https://github.com/user-attachments/assets/229450e8-d229-4cf2-b5f6-4bb6c6ca150f)
![Screenshot 2024-09-13 at 08 19 22](https://github.com/user-attachments/assets/6e54aae9-f3bd-4a8b-9832-86f1125721e1)

Though I see them in the external section.

Is this a problem because they're not defined in Cargo.toml w/ the annotation like other crate_universe options. I would like to consider vendoring in, but do wonder how locking works. Are you able to vendor in and get a locked set from a tool like Carog? In your example, the versions just seem to be picked.

**Comment by marvin-hansen** [comment]
Please share a reproduction of the issue as GitHub repo and I take a look over the weekend. I saw your slack message and explained a bit of background but for this issue I need a repo to see what can be done.

Thank you.

**Comment by zachcoleman** [comment]
> Please share a reproduction of the issue as GitHub repo and I take a look over the weekend. I saw your slack message and explained a bit of background but for this issue I need a repo to see what can be done.
> 
> Thank you.

Here's a reproducible example. I have tried to keep some of the folder structure of my work stuff https://github.com/zachcoleman/bazel-rust-reproducible-prost
running:
```
bazel run //services/hello_world_grpc_rust/server
```
will reproduce the error where it can't find the protoc stuff for the prost toolchain
if you comment out the prost toolchain registration in the MODULE file:
```
# register_toolchains("@//build_tools/prost_toolchain")
```
You can see the compilation, but failure to bazel run in a tokio runtime
