### ISSUE TITLE
Linking fails for cc_library targets with "alwayslink = 1"

### ISSUE THREAD

**Issue by dfreese** [bazelbuild/rules_rust#325]
I ran into a situation with grpc's use of c-ares, where rust_test or binary would fail to link in the appropriate object files.  This was related to the `alwayslink = 1` attribute set on the ares cc_library.

The simplest example I could reduce this to is below (which is also on my [alwayslink branch](https://github.com/dfreese/rules_rust/tree/alwayslink/test/alwayslink))

BUILD
```python
load("//rust:rust.bzl", "rust_library", "rust_test")

cc_library(
    name = "linked",
    srcs = [
        "linked.cc",
    ],
    # Compilation will fail if this is commented out.
    # alwayslink = 1,
)

rust_library(
    name = "use_linked",
    srcs = ["use_linked.rs"],
    deps = [
        ":linked",
    ],
)

rust_test(
    name = "use_linked_test",
    crate = ":use_linked",
)
```
linked.cc
```cpp
extern "C" {
int cc_value() { return 42; }
}
```

use_linked.rs
```rust
extern "C" {
    pub fn cc_value() -> ::std::os::raw::c_int;
}

pub fn value() -> i32 {
    unsafe { cc_value() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn value_works() {
        assert_eq!(value(), 42);
    }
}
```

I haven't had a chance to look into it much, but it appears to be a result of the way linker arguments are constructed.  For example, the `if l.basename.endswith(toolchain.staticlib_ext)` [here](https://github.com/bazelbuild/rules_rust/blob/master/rust/private/rustc.bzl#L143) seems to filter out any mention of `linked` completely from the linker invocation.  Changing that to `if not l.basename.endswith(toolchain.dylib_ext)]` causes an `-llinked` linker argument to show up, but this isn't entirely correct, as there should be a reference to linked.cc's object file.

**Comment by aaliddell** [comment]
I've just run into this as well, again with the upstream c-ares `cc_library` having the `alwayslink = 1` flag that cannot be easily changed. The produced library from that rule has the `.lo` extension rather than `.a` which means it will not be recognised as a valid static library due to the extension checking. Patching the line [here](https://github.com/bazelbuild/rules_rust/blob/e64700dc9b8b3869bce4f77b78c33cb9d088cc4b/rust/private/rustc.bzl#L164) to check for `.lo` gets it to produce an `-lstatic=ares` flag for the `libares.lo` file and the corresponding `-L` flag, but linking still fails as it appears the `.lo` files are not found by one of the internal tools (rustc?):

```
error: could not find native static library `ares`, perhaps an -L flag is missing?
```

Manually making a `genrule` that copies the `.lo` file to be an `.a` file and then using `cc_import` appears to work and the produced binary runs, but this may be breaking all sorts of linking rules. Note that these don't appear to be the same convention as the `.lo` files described by google searches (libtool), but rather might be a Bazel specific use? Indeed, poking around the file with objdump I can't see any immediate structural difference between a similar `.a` file produced by Bazel. I don't have the expertise on Bazel internals to determine if the files are generated the same way, but the types are defined [here](https://github.com/bazelbuild/bazel/blob/bdd08003d859c6dba027a4c3cefb18ec15a4f503/src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java#L107-L148) and don't appear to be used substantially differently elsewhere.

If the underlying tools cannot be patched to support `.lo` files (e.g if it's a rustc vs Bazel internals fight), a viable solution may be for rules_rust to copy and rename these files internally on `rust_binary`? Provided we can establish that's a permissible thing to do...
