### ISSUE TITLE
Add dev_components documentation

### ISSUE THREAD

**Issue by Arm1stice** [bazelbuild/rules_rust#363]
I think that the `dev_components` option that I added to the rust_repositories rule a few days ago is missing from the documentation since it is not auto-generated. I can make a PR to fix this tomorrow.

**Comment by damienmg** [comment]
It's missing because rust_repositories is not included in the list of generated documentation. I remember not including rust_wasm_bindgen_repostories because of some dependencies issue and I found the documentation of this rule to not be significant.

rust_repositories rule doc is better suited for that and would be great to include. To be fair there are some other module documentation that are not generated, e.g. for proto there is a module documentation, so there is a lot of room to improve that generated documentation.

**Comment by Arm1stice** [comment]
I don't think I have the time to work on this issue anymore
