### ISSUE TITLE
ci.bazel.io build is broken: missing dependency to the C++ wrapper

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_rust#4]
Latest change introduced a wrapper around gcc, which is not shiped to the sandbox, see
http://ci.bazel.io/job/rules_rust/BAZEL_VERSION=HEAD,PLATFORM_NAME=ubuntu_15.10-x86_64/74/console

**Comment by avrabe** [comment]
Fixed in commit e3882ff8. 

The solution is to remove the `#include <stdint.h>` dependency and define the required types directly in the source file. This avoids absolute path inclusion issues when building for WASI targets with Bazel sandboxing enabled.

The fix uses compiler builtins like `__SIZE_TYPE__` to ensure portability across platforms while avoiding system header dependencies that cause sandboxing conflicts with cross-compilation toolchains.

Please test with the latest commit (rebased on upstream main) and let me know if this resolves the sandboxing issue.
