### ISSUE TITLE
Consistent Library Names

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#405]
I've come across this enough and feel like I should post an issue here. 

Can someone provide some justification for why libraries produced by `rust_library` include a hash in them ([see @io_bazel_rules_rust//rust/private:rust.bzl](https://github.com/bazelbuild/rules_rust/blob/master/rust/private/rust.bzl#L30-L58)). My expectation is that the name would simply be the name of the target plus the appropriate extension. 

```rust
// Current
"libmy_target--451414955.so"
```

vs

```rust
// Expectation
"libmy_target.so"
```

I can appreciate the hash but I feel like that should instead be a symlink target or maybe a symlink should be created that uses the simple name. Maybe the hash can just be some metadata file generated with the library. Either way, I find this to be more cumbersome than helpful. 

Interested in hearing other peoples thoughts though. Again, I'd love to hear why this is the way that it is.

**Comment by acmcarther** [comment]
Yo, undead maintainer here. Thanks for your comments and PRs. This change dates back to this PR. 
https://github.com/bazelbuild/rules_rust/pull/47

I can't remember the exact problem this solves, but it's something like "rustc can't handle libraries with the exact same filename as build inputs". Before that PR, nobody knew it was an issue because nobody could compile crates from the cargo ecosystem. In the early version of raze, I found this issue, and implemented this hack.

This comment is probably the most specific framing of it
https://github.com/bazelbuild/rules_rust/pull/47#issuecomment-365492191

---

Side thing. In this case, I knew I was probably the only person that could answer this, but didn't know exactly what the answer was. Here's how I found the answer from my past self:

1. From [your link](https://github.com/bazelbuild/rules_rust/blob/master/rust/private/rust.bzl#L30-L58) I found the "determine_output_hash", which I knew was the most relevant snippet. I hit the `blame` button and saw Marco's PR here: https://github.com/bazelbuild/rules_rust/pull/123 with this commit: https://github.com/bazelbuild/rules_rust/commit/d33bf1d2d9f7f66f4c3ba854949bcf88162e36ee
2. I knew a priori that this wasn't the initial PR (you'd have to determine this yourself in a similar situation), so I went to the commit, clicked the "parent", which is this commit: https://github.com/bazelbuild/rules_rust/commit/eb4681914a5c7abd99b48c600125c3f1794594fe
3. From the parent, I browsed files
4. Then I clicked around the files (any search would work better) and found "determine_output_hash" in the ancient rust.bzl here: https://github.com/bazelbuild/rules_rust/blob/eb4681914a5c7abd99b48c600125c3f1794594fe/rust/rust.bzl#L85
5. Hit blame again
6. Landed on the commit, here https://github.com/bazelbuild/rules_rust/commit/f3a46b1395c3cebeb7d4a6df550c13f902c79134 with the PR here https://github.com/bazelbuild/rules_rust/pull/47

---

In my undead maintainer state, I'm not really against changing this, but it probably can't just result in the `libCRATE_NAME.so` or we'll have the problem that that commit was solving I think
.

**Comment by UebelAndre** [comment]
I think https://github.com/bazelbuild/rules_rust/pull/1066 satisfies the request here since I opened it while trying to load `cdylib` files. I'm happy to reopen this if someone wants to mention another use case for this 😄
