### ISSUE TITLE
RFC: Set default 'edition' to 2018

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#498]
I think this would be a very convenient thing to do. What do others think?

**Comment by mfarrugi** [comment]
Seems reasonable now, but at some point I imagine we would stop making breaking changes :). 

It might make sense to require the user to provide default_edition instead of providing a default. If nothing else, it makes it clearer that the user can control it; I noticed cxx [uses a macro](https://github.com/dtolnay/cxx/blob/master/tools/bazel/rust.bzl#L12) instead of the toolchain parameter the other day.

**Comment by UebelAndre** [comment]
Yeah, I really like the idea of applying the edition on a workspace. Spent more time than I'd like to admit debugging issues only to realize I forgot to set `edition = "2018"`.

**Comment by dae** [comment]
I think you can already mostly do that by passing edition="2018" to the rust_repositories() call?

**Comment by UebelAndre** [comment]
Oh man! How could I have forgotten about that?! That makes me happy but I still wonder if it's worth updating the default given that (from what I've gathered) `2018` is the most common edition used today. Though I do lean toward leaving it and allowing the default to be updated in some newer release of `rustc`.

**Comment by UebelAndre** [comment]
Gonna close this for now. I think this was just an oversight on my part 😅
