### ISSUE TITLE
compilation_mode changes during build for proc-macro deps

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#522]
When compiling a target in `fastbuild`, all proc-macro dependencies compile in `opt` rather than `fastbuild`. This breaks crates like rust-embed which expect to be compiled with the same settings as the crates using them. I've searched through `rules_rust` and I don't see where this could be changing. In fact, changing the very first line of `_rust_library_impl` to `print(ctx.var["COMPILATION_MODE"])` will print `opt` for proc-macro crates.

I suspect this has something to do with this code, though I don't really understand it yet. Maybe @illicitonion has more context.
https://github.com/bazelbuild/rules_rust/blob/feb8642761ba923de735a102bf43d090254b92ff/rust/private/rust.bzl#L401-L411

**Comment by illicitonion** [comment]
Interesting... That _is_ the code responsible for the transition happening, but before the change you linked to a transition to a different configuration was happening, so the same problem would've occurred - that change just changed the API used for the transition (and changed the new configuration to exec rather than host, which is definitely more correct - before, when transitioning to host, either you'd see exactly the same issue, or you'd see fastbuild being used when target was opt - I don't remember what host builds off the top of my head)... Can you point at the code which assumes it's being built in the same configuration - I'm curious what it's checking and doing...

**Comment by djmarcin** [comment]
Sure, RustEmbed is specifically what I'm working with, but there's no reason it couldn't be generally true in other crates: https://github.com/pyros2097/rust-embed/blob/master/impl/src/lib.rs

I've also come to the conclusion that your PR wouldn't have _changed_ this behavior, it was probably always this way. Having thought about it more, this just seems like a bad pattern from the proc-macro author and the best thing to do is probably to patch the crate. For example, an attribute on target cpu would be invalid, so why should an attribute on compilation mode be expected to be valid. However, cargo *does* behave this way, so we might see it in more crates.

**Comment by illicitonion** [comment]
> I've also come to the conclusion that your PR wouldn't have _changed_ this behavior, it was probably always this way. Having thought about it more, this just seems like a bad pattern from the proc-macro author and the best thing to do is probably to patch the crate. For example, an attribute on target cpu would be invalid, so why should an attribute on compilation mode be expected to be valid. However, cargo _does_ behave this way, so we might see it in more crates.

Yeah, I agree that this is a sketchy thing for a proc-macro to be depending on, but we may see it again in the future... Hopefully upstream responds well to a patch :)
