### ISSUE TITLE
Rust binaries update

### ISSUE THREAD

**Issue by lilianmoraru** [bazelbuild/rules_rust#53]
The Rust version in `rust/repositories.bzl` seems a bit old.
Would you guys please consider updating to Rust 1.20+(it seems that the archive is stored on Google's storage).
Besides the features that were released meanwhile(before the `1.20` release), `1.20` has some important things like:
- @pcwalton(Servo team) finished up the stack probes support in LLVM(for x86/x86_64) and the Rust support for them landed in `1.20` - this prevents stack overflows from going outside the application's memory.
- `-Z relro-level=[full,partial,off]` - again, for security-aware software.

**Comment by mfarrugi** [comment]
https://github.com/bazelbuild/rules_rust/pull/56 is open to update, but it would also be good to make this pluggable. Has this already been thought about?

**Comment by katre** [comment]
These can definitely be merged to update the default, but the point of the new toolchains system in Bazel is that you can define your own toolchain, with the new Rust release, and use that instead of the ones provided in the rules by default. You just need to copy the relevant rust_toolchain and toolchain rules, and instead of calling rust_repositories() in your WORKSPACE, call register_toolchains with the toolchains you've defined.

I'll assign #56 to myself and get it merged, however.

**Comment by mfarrugi** [comment]
Just to be clear, pasting `repositories.bzl` and updating parameters is the best way to do this?

**Comment by katre** [comment]
Yes, that should be fine.

**Comment by katre** [comment]
PR #56 is merged, so I am also closing this issue.
