### ISSUE TITLE
compile_data does not propagate to rust_test targets

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#567]
Given a `rust_library` target with `compile_data`, the corresponding `rust_test` will fail to compile unless the `compile_data` attribute is also included on it. It seems like this is extraneous and the `rust_library` `compile_data` should automatically be included.

**Comment by illicitonion** [comment]
Yeah, that seems like a bug - it feels like `compile_data` should be propagated to "wrapper" targets (but not to other dependees, or transitively)

**Comment by UebelAndre** [comment]
What would this fix look like? Should the [CrateInfo](https://github.com/bazelbuild/rules_rust/blob/3974550a12db8b49f4cd2e083337c55b2871779d/rust/private/providers.bzl#L17-L32) provider gain a new field `compile_data`?

cc @hlopko who might also have good insight on the impact there.

**Comment by hlopko** [comment]
just a side question, @illicitonion are there other "wrapper" targets than a `rust_test` using `crate` attr?

I agree that updating `CrateInfo` is the right solution here. Because of the design of Rust unit testing we can't avoid exposing state from all `rust_library` attributes to `rust_test` through `CrateInfo`. This issue is not surprising me, there's a bit of missing functionality there, for example I found https://github.com/bazelbuild/rules_rust/pull/751 the other day.

**Comment by hlopko** [comment]
> just a side question, @illicitonion are there other "wrapper" targets than a rust_test using crate attr?

To partially answer my own question, we also have `rust_doc` as a wrapper rule and the third discovered issue at https://github.com/bazelbuild/rules_rust/issues/689.

**Comment by illicitonion** [comment]
> just a side question, @illicitonion are there other "wrapper" targets than a `rust_test` using `crate` attr?

I don't know of any other than `rust_test` and `rust_doc`, but I'm not confident in saying there aren't others!
