### ISSUE TITLE
`build.rs` files don't detect sysroots

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_rust#659]
There may be a way to do this already, so apologies if I am unaware of it.

In looking at *ring* (https://github.com/briansmith/ring/issues/1242), I think the ideal way to build it in Bazel would be to use a `cc_library` rule instead of running its `build.rs` file. Is there a way to do that?

**Comment by illicitonion** [comment]
FWIW I've been able to successfully build `ring` with bazel using `crate_universe`, both with and without remote execution - it's possible your cc toolchain isn't configured properly to include some include search paths (or it's possible mine is too permissive and is leaking stuff it shouldn't be!)

You can currently add a dependency on the `cc_library` using an `overrides` of `extra_bazel_deps`, but you can't tell it to skip a `build.rs`. https://github.com/bazelbuild/rules_rust/blob/main/examples/crate_universe/has_aliased_deps/WORKSPACE has an example of doing something similar with `openssl` - `openssl-sys`'s build.rs allows you to opt into pointing at a specific location that a built `openssl` can be found, by setting the `OPENSSL_DIR` env var, so we do that, and point at the directory where the dep will be.

If you wanted to build `ring` as a `cc_library` I'd probably recommend taking a similar approach to `openssl` - making the `build.rs` able to detect a pre-built library, and adding it as a dep, rather than flatly skipping the whole `build.rs` - the `build.rs` may do other things that matter, so skipping it may have unforeseen consequences, either now or in the future as `ring` evolves :)

**Comment by sayrer** [comment]
> (or it's possible mine is too permissive and is leaking stuff it shouldn't be!)

That is likely the case. I'm building with https://github.com/grafica/build/blob/main/ubuntu_20_04_bazel_with_cc_toolchain/Dockerfile

along with this option:

`--incompatible_enable_cc_toolchain_resolution`

and main-branch copies of `bazel` and `rules_rust`, using this toolchain:

https://gist.github.com/sayrer/6b62c1e5385c4961635e3aedee90b6e1

The sysroot is the one that Chromium currently uses.

**Comment by illicitonion** [comment]
It looks like the differences in our environments is that we pre-install [libc6-dev](https://packages.debian.org/jessie/amd64/libc6-dev/filelist) and [linux-libc-dev](https://packages.debian.org/jessie/amd64/linux-libc-dev/filelist) and specify their paths as `cxx_builtin_include_directories`s which you don't - how are you supplying those in your toolchain?

**Comment by sayrer** [comment]
Using a toolchain as in the gist above, a sysroot that's pulled into the workspace (https://github.com/grafica/build/tree/main/sysroots/debian_sid_amd64-sysroot), and `--incompatible_enable_cc_toolchain_resolution`

**Comment by sayrer** [comment]
The patch above let's me build all of ring and rustls now.

**Comment by sayrer** [comment]
Fixed.
