### ISSUE TITLE
Add chksums for tar.xz files

### ISSUE THREAD

**Issue by wt** [bazelbuild/rules_rust#871]
I would like to see some support for tar.xz files since they compress way better. The known file chksums currently only chksum the tar.gz files. This will require some refactoring I guess.

I think we have a couple options to get this in place.

1. Make the FILE_KEY_TO_SHA dict keys include the extensions and make the lookups use the proper keys that include the extensions.
2. Not support tar.xz files, which would be a bummer.

I would love to know if there are ways to plumb this through.

Thanks.

**Comment by illicitonion** [comment]
This sounds like a good improvement, and like a reasonable approach. I think the steps I'd take to go about this are:
1. Add a new attribute to the `rust_toolchain_repository` `repository_rule`, called `type` to mirror `https://docs.bazel.build/versions/main/repo/http.html#http_archive-type` - for now I guess let's let it take values `tar.gz` or `tar.xz`, and default to `tar.gz`.
2. Instead of a single `DEFAULT_STATIC_RUST_URL_TEMPLATES`, derive that value based on the `type` attribute.
3. Assume that if someone is explicitly overriding their template, their value doesn't need any modifying - if they want to switch to `tar.xz`, they should modify their template, as well as setting the `type` attr.
4. Make `FILE_KEY_TO_SHA` either have a tuple as a key, or be a two-level dict, and modify `util/fetch_shas.sh` to generate the dict
5. Update all of the call sites accordingly

Feel free to reach out here or [on slack](https://bazelbuild.slack.com/archives/CSV56UT0F) if you need a hand!
