### ISSUE TITLE
Statically compile (C++) process wrapper

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#893]
After a recent thread in slack, it sounds like the process wrapper is not being statically compiled? I would have assumed this was the case. Is there a way to do this in a cross platform way?

**Comment by UebelAndre** [comment]
@hlopko Do you know if it is or is not being statically compiled?

**Comment by wt** [comment]
I'll try to add some context here.

I was trying to enable the rust rules at my work. Our toolchain includes a custom gcc toolchain that we add to the front of the PATH and adds lib dirs to LD_LIBRARY_PATH. Apparently, bazel will pick up the g++ binary for the compile, but it will not pick up the LD_LIBRARY_PATH when running the process wrapper during a build. I know this because I got an error about the libstdc++ not having the newer ABI version from our custom built toolchain. I had to manually plumb the LD_LIBRARY_PATH in, which felt wrong if the compile of the process wrapper worked.

**Comment by sayrer** [comment]
You probably need to set up a `cc_toolchain`. See https://github.com/grafica/crustls/tree/cc_toolchain. (WORKSPACE, .bazelrc) and https://github.com/grailbio/bazel-toolchain/.

The way I'd recommend hacking on this is to set up a VM without any devtools installed, and iterate until you can download all of your toolchain dependencies. A default Ubuntu install works fine for this (just don't apt-get anything).

**Comment by hlopko** [comment]
So, process wrapper is a C++ binary so it's built using the C++ toolchain. I'd say that if you`re using LD_LIBRARY_PATH then Bazel's autoconfigured C++ toolchain is very likely not picking it up and it should be fixed either in Bazel, or on your end (by creating your own C++ toolchain config for Bazel, which is TBH quite an endeavor). Those 2 are the principled solutions.

For workarounds:

1) Pass `--repo_env=CC-/your/other/gcc` to Bazel if you don't care about what C++ compiler is used to build tools used by rules_rust.

2) Pass `--action_env=LD_LIBRARY_PATH=...` Bazel option if you want it to be set for all actions Bazel runs. That should make your process wrapper work.

**Comment by wt** [comment]
Option 2 did not work. I already tried that.

It appears that the rust rules must explicitly add that variable to the environ to get access to it. In #900 you can see that I did that in order to work around this problem. I am wondering if there is a better solution.

**Comment by wt** [comment]
As for option 1, I would like to use whatever toolchain is use for c++ compiles instead of overriding it for this tool.

**Comment by hlopko** [comment]
@wt I'm a bit confused. Do you build any C++ binary with Bazel using your gcc toolchain from PATH (other than process_wrapper)? 

Process_wrapper is not special in any way, it is just a C++ binary built by Bazel and executed during the build. You don't have to do anything special to configure the build for the process wrapper as long as Bazel's C++ toolchain is configured correctly for other C++ binaries. It will be the same Bazel C++ toolchain compiling and linking all your cc_binaries and the process wrapper.

**Comment by wt** [comment]
The build host installs a custom-built gcc (not binutils) and adds it to the front of the path (something like /custom-gcc/bin/) and to the LD_LIBRARY_PATH (something like /custom-gcc/lib, which includes libstdc++). When the binary is built, it links against the custom libs (in the /custom-gcc/lib dir). When I try to build rust (which runs the tool), the tool fails to run because the custom libstdc++ it was linked against has a newer ABI than the one in /usr/lib and the LD_LIBRARY_PATH var is not set in the tool's environment. Take a look at the draft PR, which works around this issue.

Static linking was suggested as a workaround for the issue so that it didn't improperly try to use the /usr/lib version of libstdc++ when running (due to LD_LIBRARY_PATH not being set in the tool's environment).

As for myself, I am not sure if this is reasonable or not as a fix, I wanted to share the problem I was facing to see what we could do to make it better.

**Comment by wt** [comment]
Also, we do not have a cc_toolchain defined in our bazel config. We do use the version on path for it.

If that can fix it somehow, I am open to it, but it's not clear to me how that would fix anything since it would have the same problem with the LD_LIBRARY_PATH env var.

**Comment by wt** [comment]
I honestly think we should close this. It is not clear to me that this is the right solution for the problem at hand.

**Comment by UebelAndre** [comment]
> I honestly think we should close this. It is not clear to me that this is the right solution for the problem at hand.

Thanks for pinging the issue. We can close this since I also don't know the right solution. I'm happy to reopen it or defer to a newer issue if the effort comes back up 😄
